### ISSUE TITLE
No README.md in the Repo

### ISSUE THREAD

**Issue by Robbie-Cook** [CloudCannon/stretcher#1]
@bigelowcc There should probably be a README with simple instuctions, a nice image, badges, and a link to the website.

Happy to help if needed :)

**Comment by bglw** [comment]
Added the README with instructions. Feel free to contribute a nice image or badges

**Comment by Robbie-Cook** [comment]
Great! Thanks @bigelowcc , wil take a look

**Comment by Robbie-Cook** [comment]
Awesome!
